version: '3'
services:
  blog_next_backend:
    container_name: blog_next_backend
    #指定构建的Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
      #工作目录空间
    working_dir: /go/src/github.com/blog_backend
    volumes:
    #jenkins执行的时候，   ./是项目的路径
    - ./:/go/src/github.com/blog_backend
    - /home/xiaochen/BlogNext/code/Blog_Backend/upload:/go/bin/upload
    - /home/xiaochen/BlogNext/code/Blog_Backend/config/:/go/bin/config
    command: /bin/bash -c "go install -v ./ && /go/bin/blog_backend"
    ports:
    - "8083:8083"
    networks:
    - blog_next
networks:
  blog_next:
    external: true