version: '3'
services:
  blog_next_backend:
    container_name: blog_next_backend
    #指定构建的Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
      #工作目录空间
    working_dir: /go/src/Blog_Backend/my-gin
    volumes:
    #jenkins执行的时候，   ./是项目的路径
    - ./:/go/src/Blog_Backend/my-gin
    - /home/xiaochen/BlogNext/code/Blog_Backend/upload:/go/bin/upload
    - /home/xiaochen/BlogNext/code/Blog_Backend/config/:/go/bin/config
    command: [go, install, -v, ./...]
    #设置环境变量
    environment:
    - GOPROXY=https://mirrors.aliyun.com/goproxy/
    networks:
    - blog_next
networks:
  blog_next:
    external: true